<?php

/**
 * Swagger Petstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class PetsController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation createPets
     *
     * Create a pet.
     *
     *
     * @return Http response
     */
    public function createPets()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing createPets as a post method ?');
    }
    /**
     * Operation listPets
     *
     * List all pets.
     *
     *
     * @return Http response
     */
    public function listPets()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $limit = $input['limit'];


        return response('How about implementing listPets as a get method ?');
    }
    /**
     * Operation showPetById
     *
     * Info for a specific pet.
     *
     * @param string $petId The id of the pet to retrieve (required)
     *
     * @return Http response
     */
    public function showPetById($petId)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing showPetById as a get method ?');
    }
}
